sudo: required
language: generic
branches:
  except:
  - master
services:
  - docker

before_install:
  - docker build -t matipacheco/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true matipacheco/docker-react npm run test -- --coverage