sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t matipacheco/docker-react -f 3-react-app-production-deploy-workflow/Dockerfile.dev .

script:
  - docker run -e CI=true matipacheco/docker-react npm run test -- --coverage