FROM node:alpine

WORKDIR "/app"

COPY package.json .
RUN npm install

COPY . .

CMD [ "npm", "run", "start" ]

# This image should be build using the -f option.
# -f specifies the file that will be used to build the image.
# docker build -f Dockerfile.dev .

# To not have to be building the container every time there's a change in the React app code,
# We could set a Docker Volume. Volumes are a way to map folders inside the container, to folders
# in your local machine. Similar to what we do with ports.
# docker run -it -p 3000:3000 -v /app/node_modules -v $(pwd):/add IMAGE_ID